version: "3.8"
services:
  futy-t3-db:
    restart: always
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  futy-t3-next:
    depends_on:
      - futy-t3-db
    restart: unless-stopped
    image: ghcr.io/eliasablan/futy-t3:latest
    ports:
      - 5005:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_FBDO_API_KEY=${NEXT_PUBLIC_FBDO_API_KEY}
      - NEXT_PUBLIC_FBDO_URL=${NEXT_PUBLIC_FBDO_URL}
networks: {}
volumes:
  db: null
