version: "3.8"
services:
  futy-t3-db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - next-futy
  futy-t3-next:
    image: ghcr.io/eliasablan/futy-t3:latest
    ports:
      - 5005:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_FBDO_API_KEY=${NEXT_PUBLIC_FBDO_API_KEY}
      - NEXT_PUBLIC_FBDO_URL=${NEXT_PUBLIC_FBDO_URL}
    depends_on:
      - futy-t3-db
    networks:
      - next-futy
volumes:
  db: null
x-dockge:
  urls:
    - https://futy.eliasablan.com
networks:
  next-futy:
    driver: bridge
